image: node:latest


pipelines:
  branches:
    development:
      - step:
          name: Build
          script:
            - npm install
      - step:
          name: Deploy to EC2
          script:
          - chmod +x execute.sh
          - ./execute.sh     

      # - step:
      #     name: Deploy to Cloud Server
      #     script:
      #       - ./deploy-script.sh # replace with your deployment script
